steps:  
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: bash
    args: 
      - -c
      - |
        ./dev/change_scala_version.sh 2.11
        mvn clean package -Pspark-2.3 -Pscala-2.11 -DskipTests -Pbuild-distr -Phadoop2     

  - name: debian
    entrypoint: bash
    args:
      - -c
      - |
        mv zeppelin-distribution/target/zeppelin-*.tar.gz scripts/docker/zeppelin/bin/  

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        cd scripts/docker/zeppelin/bin/ && docker build -t gcr.io/$PROJECT_ID/zeppelin:0.9.0-SNAPSHOT         

tags: ['cloud-build-spark']
images: ['gcr.io/$PROJECT_ID/zeppelin']

